-- Migration script to create the categories table
-- Run this script in your Supabase SQL editor

-- Create the categories table
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  image_url TEXT
);

-- Insert all categories
INSERT INTO categories (name, image_url) VALUES
('pottery', 'assets/pottery.png'),
('painting', 'assets/painting.png'),
('drawing', 'assets/drawing.png'),
('portraits', 'assets/portraits.png'),
('jewellery', 'assets/jewellery.png'),
('clothes', 'assets/clothing.png'),
('wood carving', 'assets/wood_carving.png'),
('digital art', 'assets/digital_art.png'),
('embroidery', 'assets/embroidery.png'),
('glass art', 'assets/glass_art.png'),
('glass etching', 'assets/glass_etching.png'),
('candle making', 'assets/candle_making.png'),
('furniture', 'assets/furniture.png'),
('basket weaving', 'assets/basket_weaving.png'),
('calligraphy', 'assets/calligraphy.png'),
('air dry clay toy making', 'assets/air_dry_clay_toy.png'),
('miniature arts', 'assets/miniature_arts.png'),
('crochet', 'assets/crochet.png'),
('knitting', 'assets/knitting.png'),
('folk art', 'assets/folk_art.png'),
('leather craft', 'assets/leather_craft.png'),
('scrimshaw', 'assets/scrimshaw.png'),
('macrame', 'assets/macrame.png'),
('metalworking', 'assets/metalworking.png'),
('nature crafts', 'assets/nature_crafts.png'),
('paper marbling', 'assets/paper_marbling.png'),
('phone cases', 'assets/phone_cases.png'),
('quilting', 'assets/quilting.png'),
('rugs', 'assets/rugs.png'),
('scrapbooking', 'assets/scrapbooking.png'),
('soap making', 'assets/soap_making.png'),
('t-shirt art', 'assets/tshirt_art.png'),
('wall hangings', 'assets/wall_hangings.png'),
('quilling', 'assets/quilling.png'),
('origami', 'assets/origami.png'),
('resin art', 'assets/resin_art.png'),
('mosaic art', 'assets/mosaic_art.png'),
('mixed media art', 'assets/mixed_media_art.png'),
('stained glass art', 'assets/stained_glass_art.png'),
('sculpting', 'assets/sculpting.png'),
('upcycled art', 'assets/upcycled_art.png'),
('fabric painting', 'assets/fabric_painting.png'),
('beadwork', 'assets/beadwork.png'),
('decoupage', 'assets/decoupage.png'),
('string art', 'assets/string_art.png'),
('graffiti (traditional)', 'assets/graffiti_traditional.png'),
('henna / mehndi art', 'assets/henna_mehndi_art.png'),
('collage art', 'assets/collage_art.png'),
('pyrography (wood burning)', 'assets/pyrography.png'),
('papier-mâché', 'assets/papier_mache.png'),
('shell art', 'assets/shell_art.png'),
('flower pressing & leaf art', 'assets/flower_pressing_leaf_art.png'),
('others', '');
