-- Create the reviews table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    reviewee_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    reviewer_role TEXT NOT NULL CHECK (reviewer_role IN ('artist', 'customer')),
    subject TEXT NOT NULL,
    rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    description TEXT NOT NULL,
    image_urls TEXT[],
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id ON reviews(reviewer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewee_id ON reviews(reviewee_id);

-- Add comments to the table and columns
COMMENT ON TABLE reviews IS 'Stores reviews written by artists about customers and by customers about artists.';
COMMENT ON COLUMN reviews.reviewer_id IS 'The ID of the user who wrote the review.';
COMMENT ON COLUMN reviews.reviewee_id IS 'The ID of the user who is being reviewed.';
COMMENT ON COLUMN reviews.reviewer_role IS 'The role of the reviewer (artist or customer).';
COMMENT ON COLUMN reviews.subject IS 'The subject of the review.';
COMMENT ON COLUMN reviews.rating IS 'The rating given, from 1 to 5.';
COMMENT ON COLUMN reviews.description IS 'The detailed description of the review.';
COMMENT ON COLUMN reviews.image_urls IS 'An array of URLs for images uploaded with the review.';
